"""Add task domain

Revision ID: 158db9bb51ea
Revises: 
Create Date: 2026-03-13 19:41:50.964631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158db9bb51ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###